<?php

/**
 * AddressType
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * AddressType Class Doc Comment
 *
 * @category Class
 * @description Type of the address. Only some of the types are allowed in each context.
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressType
{
    /**
     * Possible values of this enum
     */
    
    const PERMANENT = 'PERMANENT';
    
    const CONTACT = 'CONTACT';
    
    const DELIVERY = 'DELIVERY';
    
    const BILLING = 'BILLING';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PERMANENT,
            self::CONTACT,
            self::DELIVERY,
            self::BILLING,
        ];
    }
}

