<?php

/**
 * DeliveryType
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * DeliveryType Class Doc Comment
 *
 * @category Class
 * @description Delivery type, for &#x60;DELIVERY_CARRIER&#x60; type can be further specified by &#x60;deliveryCarrier&#x60; attribute.
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryType
{
    /**
     * Possible values of this enum
     */
    
    const DELIVERY_CARRIER = 'DELIVERY_CARRIER';
    
    const PERSONAL_BRANCH = 'PERSONAL_BRANCH';
    
    const PERSONAL_PARTNER = 'PERSONAL_PARTNER';
    
    const ONLINE = 'ONLINE';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELIVERY_CARRIER,
            self::PERSONAL_BRANCH,
            self::PERSONAL_PARTNER,
            self::ONLINE,
        ];
    }
}

