<?php

/**
 * DeliveryCarrier
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * DeliveryCarrier Class Doc Comment
 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryCarrier
{
    /**
     * Possible values of this enum
     */
    
    const CZ_POST_HAND = 'CZ_POST_HAND';
    
    const CZ_POST_OFFICE = 'CZ_POST_OFFICE';
    
    const CZ_POST_OTHER = 'CZ_POST_OTHER';
    
    const PPL = 'PPL';
    
    const DPD = 'DPD';
    
    const GEIS = 'GEIS';
    
    const IN_TIME = 'IN_TIME';
    
    const TOP_TRANS = 'TOP_TRANS';
    
    const GEBRUDER_WEISS = 'GEBRUDER_WEISS';
    
    const LOCAL_COURIER = 'LOCAL_COURIER';
    
    const TNT = 'TNT';
    
    const GLS = 'GLS';
    
    const HDS_COMFORT = 'HDS_COMFORT';
    
    const HDS_STANDARD = 'HDS_STANDARD';
    
    const MALL_DEPOSIT = 'MALL_DEPOSIT';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CZ_POST_HAND,
            self::CZ_POST_OFFICE,
            self::CZ_POST_OTHER,
            self::PPL,
            self::DPD,
            self::GEIS,
            self::IN_TIME,
            self::TOP_TRANS,
            self::GEBRUDER_WEISS,
            self::LOCAL_COURIER,
            self::TNT,
            self::GLS,
            self::HDS_COMFORT,
            self::HDS_STANDARD,
            self::MALL_DEPOSIT,
        ];
    }
}

