<?php

/**
 * ItemType
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * ItemType Class Doc Comment
 *
 * @category Class
 * @description Item type
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemType
{
    /**
     * Possible values of this enum
     */
    
    const PHYSICAL = 'PHYSICAL';
    
    const DISCOUNT = 'DISCOUNT';
    
    const SHIPPING_FEE = 'SHIPPING_FEE';
    
    const SALES_TAX = 'SALES_TAX';
    
    const DIGITAL = 'DIGITAL';
    
    const GIFT_CARD = 'GIFT_CARD';
    
    const STORE_CREDIT = 'STORE_CREDIT';
    
    const FEE = 'FEE';
    
    const INSURANCE = 'INSURANCE';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PHYSICAL,
            self::DISCOUNT,
            self::SHIPPING_FEE,
            self::SALES_TAX,
            self::DIGITAL,
            self::GIFT_CARD,
            self::STORE_CREDIT,
            self::FEE,
            self::INSURANCE,
        ];
    }
}

