<?php

/**
 * OrderDeliveryState
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * OrderDeliveryState Class Doc Comment
 *
 * @category Class
 * @description Order state.
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderDeliveryState
{
    /**
     * Possible values of this enum
     */
    
    const PROCESSING = 'PROCESSING';
    
    const SENT = 'SENT';
    
    const DELIVERED = 'DELIVERED';
    
    const RETURNED = 'RETURNED';
    
    const CANCELLED = 'CANCELLED';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PROCESSING,
            self::SENT,
            self::DELIVERED,
            self::RETURNED,
            self::CANCELLED,
        ];
    }
}

