<?php

/**
 * PrecheckResultResponseSerializer
 *
 * Skip Pay API for partners
 *
 * API documentation for Skip Pay partners.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@skippay.cz
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0

 *
 * @category Class
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkipPay\Model;
use SkipPay\ObjectSerializer;

/**
 * PrecheckResultResponseSerializer Class Doc Comment
 *
 * @category Class
 * @description Customer type.
 * @package  SkipPay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrecheckResultResponseSerializer
{
    /**
     * Possible values of this enum
     */
    
    const UNKNOWN = 'UNKNOWN';
    
    const FIRST_ORDER = 'FIRST_ORDER';
    
    const FULL = 'FULL';
    
    const BLOCKED = 'BLOCKED';
    

    /**
     * Gets allowable values of the enum.
     *
     * @return scalar[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::FIRST_ORDER,
            self::FULL,
            self::BLOCKED,
        ];
    }
}

